---
title: "Laby_Pacbio"
author: "Clarence Sim"
date: "7/4/2022"
output: html_document
---

```{r knitr_init, echo=FALSE, cache=FALSE}

library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               eval = TRUE)
opts_knit$set(width=75)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

```

```{r}

library(ggplot2); packageVersion("ggplot2")
library(stringr)
library(readxl)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(patchwork)
```


# Cell size
```{r fig.width=10, fig.height=10}
cell_size <- read_xlsx("./cell_size.xlsx") 
length.mean=mean(cell_size$length_um)
width.mean=mean(cell_size$width_um)

cell_size_long <- cell_size %>%
  mutate(Length=length_um,Width=width_um) %>%
  pivot_longer(cols=c(Length,Width),names_to = "group",values_to = "length")

plot <- ggplot(cell_size_long, aes(x=length, fill=group)) + 
  geom_histogram(color="black",binwidth = 0.2,alpha=0.8) +
  geom_vline(xintercept = length.mean, linetype="dashed", size=1, color="#004E8A") + 
  geom_vline(xintercept = width.mean, linetype="dashed", size=1, color="#B87800") + 
  theme_classic() +
  theme(text=element_text(size=20),
        legend.position="top",
        legend.title = element_blank()) +
  xlab(expression("Cell size (" * mu * "m)")) +
  scale_x_continuous(breaks = seq(2,14,1)) +
  scale_fill_manual(breaks=c("Width","Length"), values=c("#B87800","#004E8A"))
plot

pdf("./cell_size.pdf", height=7, width=10); plot(plot); dev.off() 

```

